import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { getQueryFn } from "@/lib/queryClient";
import QueryInterface from "@/components/query-interface";
import TimelineVisualization from "@/components/timeline-visualization";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Button } from "@/components/ui/button";
import { GitBranch, Download } from "lucide-react";
import type { Repository, ChangeEvent, Query } from "@shared/schema";

interface AnalysisDashboardProps {
  repository: Repository;
}

export default function AnalysisDashboard({ repository }: AnalysisDashboardProps) {
  const { data: changeEvents = [] } = useQuery({
    queryKey: ["/api/repositories", repository.id, "events"],
    queryFn: getQueryFn<ChangeEvent[]>({ on401: "throw" }),
  });

  const { data: recentQueries = [] } = useQuery({
    queryKey: ["/api/repositories", repository.id, "queries"],
    queryFn: getQueryFn<Query[]>({ on401: "throw" }),
  });

  const exportReport = () => {
    const reportData = {
      repository: {
        name: repository.name,
        url: repository.url,
        description: repository.description,
        lastAnalyzed: repository.lastAnalyzedAt,
        commitCount: repository.commitCount,
        contributorCount: repository.contributorCount,
        fileCount: repository.fileCount,
        confidenceScore: repository.confidenceScore,
      },
      summary: {
        totalChangeEvents: changeEvents.length,
        majorFeatures: repository.majorFeatureCount,
        categoriesBreakdown: getCategoryStats(),
      },
      changeEvents: changeEvents.map(event => ({
        title: event.title,
        description: event.description,
        category: event.category,
        rationale: event.rationale,
        businessImpact: event.businessImpact,
        timestamp: event.timestamp,
        commitShas: event.commitShas,
        filesAffected: event.filesAffected,
      })),
      recentQueries: recentQueries.map(query => ({
        question: query.question,
        answer: query.answer,
        confidence: 95, // Default confidence for export
        timestamp: query.createdAt,
      })),
      metadata: {
        exportedAt: new Date().toISOString(),
        exportedBy: 'Codebase Time Machine',
        version: '1.0',
      }
    };

    // Generate comprehensive text report
    const textReport = `
# Codebase Time Machine Analysis Report

## Repository Overview
- **Name:** ${repository.name}
- **URL:** ${repository.url}
- **Description:** ${repository.description || 'No description available'}
- **Analysis Date:** ${repository.lastAnalyzedAt ? new Date(repository.lastAnalyzedAt).toLocaleDateString() : 'Unknown'}

## Statistics
- **Total Commits:** ${repository.commitCount}
- **Contributors:** ${repository.contributorCount}
- **Files Analyzed:** ${repository.fileCount}
- **Confidence Score:** ${repository.confidenceScore}%
- **Change Events Identified:** ${changeEvents.length}
- **Major Features:** ${repository.majorFeatureCount}

## Change Categories Breakdown
${getCategoryStats().map(stat => `- **${stat.name}:** ${stat.count}`).join('\n')}

## Major Change Events

${changeEvents.filter(event => event.category === 'new_feature').slice(0, 10).map((event, index) => `
### ${index + 1}. ${event.title}
- **Category:** ${event.category}
- **Business Impact:** ${event.businessImpact}
- **Rationale:** ${event.rationale}
- **Files Affected:** ${event.filesAffected?.join(', ') || 'N/A'}
- **Commits:** ${event.commitShas?.join(', ') || 'N/A'}
`).join('\n')}

## Recent Analysis Queries

${recentQueries.slice(0, 5).map((query, index) => `
### Query ${index + 1}: ${query.question}
**Answer:** ${query.answer}
**Confidence:** 95%
**Asked:** ${new Date(query.createdAt).toLocaleDateString()}
`).join('\n')}

## Export Information
- **Exported At:** ${new Date().toLocaleString()}
- **Generated By:** Codebase Time Machine v1.0
`;

    // Create and download the report
    const blob = new Blob([textReport], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${repository.name.replace(/[^a-zA-Z0-9]/g, '_')}_analysis_report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    // Also offer JSON download
    const jsonBlob = new Blob([JSON.stringify(reportData, null, 2)], { type: 'application/json' });
    const jsonUrl = URL.createObjectURL(jsonBlob);
    const jsonLink = document.createElement('a');
    jsonLink.href = jsonUrl;
    jsonLink.download = `${repository.name.replace(/[^a-zA-Z0-9]/g, '_')}_analysis_data.json`;
    document.body.appendChild(jsonLink);
    jsonLink.click();
    document.body.removeChild(jsonLink);
    URL.revokeObjectURL(jsonUrl);
  };

  const getCategoryStats = () => {
    const stats = changeEvents.reduce((acc, event) => {
      acc[event.category] = (acc[event.category] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    return [
      { name: "New Features", count: stats.new_feature || 0, color: "bg-green-500" },
      { name: "Enhancements", count: stats.enhancement || 0, color: "bg-blue-500" },
      { name: "Bug Fixes", count: stats.bug_fix || 0, color: "bg-red-500" },
      { name: "Refactoring", count: stats.refactoring || 0, color: "bg-gray-500" },
    ];
  };

  const categoryStats = getCategoryStats();

  return (
    <div className="min-h-screen">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Repository Overview Header */}
        <Card className="glass-card mb-10 overflow-hidden pulse-glow">
          <CardContent className="p-10">
            <div className="flex items-start justify-between">
              <div className="flex items-start space-x-8">
                <div className="w-20 h-20 premium-gradient rounded-3xl flex items-center justify-center shadow-2xl floating">
                  <GitBranch className="text-white w-10 h-10" />
                </div>
                <div>
                  <h2 className="text-3xl font-bold gradient-text mb-3" data-testid="text-repository-name">
                    {repository.name}
                  </h2>
                  {repository.description && (
                    <p className="text-slate-600 text-xl mb-4 max-w-2xl leading-relaxed" data-testid="text-repository-description">
                      {repository.description}
                    </p>
                  )}
                  <div className="flex items-center space-x-8 text-sm">
                    <div className="flex items-center space-x-3 bg-blue-50 px-4 py-2 rounded-full">
                      <div className="w-3 h-3 bg-blue-500 rounded-full shadow-sm"></div>
                      <span className="text-slate-700 font-semibold" data-testid="text-commit-count">{repository.commitCount} commits</span>
                    </div>
                    <div className="flex items-center space-x-3 bg-green-50 px-4 py-2 rounded-full">
                      <div className="w-3 h-3 bg-green-500 rounded-full shadow-sm"></div>
                      <span className="text-slate-700 font-semibold" data-testid="text-contributor-count">{repository.contributorCount} contributors</span>
                    </div>
                    <div className="flex items-center space-x-3 bg-purple-50 px-4 py-2 rounded-full">
                      <div className="w-3 h-3 bg-purple-500 rounded-full shadow-sm"></div>
                      <span className="text-slate-700 font-semibold" data-testid="text-analyzed-time">
                        Analyzed {repository.lastAnalyzedAt ? new Date(repository.lastAnalyzedAt).toLocaleDateString() : 'recently'}
                      </span>
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex items-center space-x-3">
                <Button 
                  variant="outline" 
                  size="lg" 
                  onClick={exportReport}
                  className="bg-white/70 border-slate-300 hover:bg-white hover:shadow-xl transition-all duration-300 hover:scale-105 backdrop-blur-sm"
                  data-testid="button-export-report"
                >
                  <Download className="w-5 h-5 mr-3" />
                  Export Report
                </Button>
              </div>
          </div>
        </CardContent>
      </Card>

        <div className="grid lg:grid-cols-3 gap-10">
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-8">
            <QueryInterface repositoryId={repository.id} />
            <TimelineVisualization events={changeEvents} />
          </div>

          {/* Sidebar */}
          <div className="space-y-8">
          {/* Analysis Summary */}
          <Card className="enhanced-card">
            <CardContent className="p-8">
              <h3 className="text-xl font-semibold text-gray-900 mb-6 flex items-center">
                <div className="w-2 h-6 bg-gradient-to-b from-blue-500 to-purple-600 rounded-full mr-3"></div>
                Analysis Summary
              </h3>
              
              <div className="space-y-5">
                <div className="flex justify-between items-center p-3 rounded-lg bg-gradient-to-r from-blue-50 to-blue-100 border border-blue-200">
                  <span className="text-gray-700 font-medium">Total Commits</span>
                  <span className="font-bold text-blue-700 text-lg" data-testid="text-total-commits">{repository.commitCount}</span>
                </div>
                <div className="flex justify-between items-center p-3 rounded-lg bg-gradient-to-r from-green-50 to-green-100 border border-green-200">
                  <span className="text-gray-700 font-medium">Contributors</span>
                  <span className="font-bold text-green-700 text-lg" data-testid="text-total-contributors">{repository.contributorCount}</span>
                </div>
                <div className="flex justify-between items-center p-3 rounded-lg bg-gradient-to-r from-purple-50 to-purple-100 border border-purple-200">
                  <span className="text-gray-700 font-medium">Files Analyzed</span>
                  <span className="font-bold text-purple-700 text-lg" data-testid="text-files-analyzed">{repository.fileCount}</span>
                </div>
                <div className="flex justify-between items-center p-3 rounded-lg bg-gradient-to-r from-indigo-50 to-indigo-100 border border-indigo-200">
                  <span className="text-gray-700 font-medium">Change Events</span>
                  <span className="font-bold text-indigo-700 text-lg" data-testid="text-change-events">{changeEvents.length}</span>
                </div>
                <div className="flex justify-between items-center p-3 rounded-lg bg-gradient-to-r from-orange-50 to-orange-100 border border-orange-200">
                  <span className="text-gray-700 font-medium">Major Features</span>
                  <span className="font-bold text-orange-700 text-lg" data-testid="text-major-features">{repository.majorFeatureCount}</span>
                </div>
              </div>

              <div className="mt-8 pt-6 border-t border-gray-200">
                <div className="text-sm">
                  <div className="flex justify-between mb-4">
                    <span className="text-gray-700 font-medium">Analysis Confidence</span>
                    <span className="font-bold text-green-600 text-lg" data-testid="text-confidence-score">
                      {repository.confidenceScore}%
                    </span>
                  </div>
                  <div className="relative">
                    <Progress value={repository.confidenceScore} className="h-3 bg-gray-200" />
                    <div className="absolute inset-0 rounded-full bg-gradient-to-r from-green-400 to-green-600 shadow-sm" 
                         style={{ width: `${repository.confidenceScore}%` }}></div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Change Categories */}
          <Card className="enhanced-card">
            <CardContent className="p-8">
              <h3 className="text-xl font-semibold text-gray-900 mb-6 flex items-center">
                <div className="w-2 h-6 bg-gradient-to-b from-purple-500 to-pink-600 rounded-full mr-3"></div>
                Change Categories
              </h3>
              
              <div className="space-y-4">
                {categoryStats.map((category) => (
                  <div key={category.name} className="flex items-center justify-between p-4 rounded-xl bg-white/50 border border-gray-100 hover:shadow-md transition-all duration-200" data-testid={`category-${category.name.toLowerCase().replace(' ', '-')}`}>
                    <div className="flex items-center space-x-4">
                      <div className={`w-4 h-4 ${category.color} rounded-full shadow-sm`} />
                      <span className="font-medium text-gray-800">{category.name}</span>
                    </div>
                    <span className="text-lg font-bold text-gray-700 bg-gray-100 px-3 py-1 rounded-full">{category.count}</span>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Recent Queries */}
          <Card className="enhanced-card">
            <CardContent className="p-8">
              <h3 className="text-xl font-semibold text-gray-900 mb-6 flex items-center">
                <div className="w-2 h-6 bg-gradient-to-b from-green-500 to-teal-600 rounded-full mr-3"></div>
                Recent Queries
              </h3>
              
              <div className="space-y-4">
                {recentQueries.slice(-3).reverse().map((query) => (
                  <button
                    key={query.id}
                    className="w-full text-left p-4 rounded-xl hover:bg-gradient-to-r hover:from-blue-50 hover:to-purple-50 border border-gray-100 hover:border-blue-200 transition-all duration-300 hover:shadow-lg"
                    data-testid={`query-${query.id}`}
                  >
                    <div className="text-sm font-semibold text-gray-900 mb-2 truncate leading-relaxed">
                      "{query.question}"
                    </div>
                    <div className="text-xs text-gray-500 bg-gray-100 px-2 py-1 rounded-full inline-block">
                      {new Date(query.createdAt).toLocaleTimeString()}
                    </div>
                  </button>
                ))}
                {recentQueries.length === 0 && (
                  <div className="text-center py-8">
                    <div className="w-16 h-16 bg-gradient-to-br from-blue-100 to-purple-100 rounded-full flex items-center justify-center mx-auto mb-4">
                      <span className="text-2xl">💭</span>
                    </div>
                    <p className="text-gray-500 font-medium">
                      No queries yet. Ask your first question!
                    </p>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
          </div>
        </div>
      </div>
    </div>
  );
}
